### ISSUE TITLE
Error when checking out for free level

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-slack#8]
Warning: in_array() expects parameter 2 to be array, 
![image (9)](https://user-images.githubusercontent.com/22073464/107047020-033b2b80-67d0-11eb-947e-35439d408eaf.png)

**Comment by michaelbeil** [comment]
This happens on a paid level as well, and was encountered by a customer (ticket 436672), and I was able to replicate it. PR https://github.com/strangerstudios/pmpro-slack/pull/9 fixes the error.
